<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Actions\ImportClipAction;
use App\Enums\Clips\ClipStatus;
use App\Enums\Clips\CompilationClipClaimStatus;
use App\Enums\Clips\CompilationStatus;
use App\Enums\Clips\CompilationType;
use App\Jobs\ImportCategoryJob;
use App\Models\Clip;
use App\Models\Clip\Compilation;
use App\Models\Scopes\ClipPermissionScope;
use App\Models\User;
use App\Services\Twitch\Data\ClipDto;
use App\Services\Twitch\TwitchService;
use Exception;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Log;

class InitialEpisodeSeeder extends Seeder
{
    // Regex to replace full urls with Slugs: 'http.+/([A-Z][a-zA-Z0-9]*-[a-zA-Z0-9_-]+)',
    // Replace with: '$1',

    // Only raw clip ids pls
    protected const array Clips = [
        // Episode 1
        'ArbitraryMuddyTomatoVoteYea-URKp4wkFAxFXh6jq',
        'JollyUnusualKuduBudBlast-rCtPoY1KJJsVd-2_',
        'LazyAliveCroissantAMPTropPunch-UosBLCxh8lpIyHwg',
        'DeterminedGleamingMooseHotPokket-jp6PZREvcUDYM4aK',
        'CooperativeBeautifulCourgetteNomNom-Xmm8Lg18BzVewWdR',
        'DependablePreciousDootKappaClaus-BSAcRgIl9k_HYzAI',
        'AgileFurryPlumberBigBrother-NectoRiE70STavvR',
        'FaithfulSpoopyTortoiseTakeNRG-tvo9yVbXy9PoshUq',
        'ClumsyGloriousNightingaleTooSpicy-0U-EAoDIXzzKB9rS',
        'CleverFaithfulWatercressTF2John-cu8rRTahL8ATnnMA',
        'SpookyProductivePhoneSwiftRage-3J7WJVEn-vypPHdx',
        'CreativeTalentedAniseTBTacoRight--zmezpz1T3vNI1Z8',
        'AgitatedWrongMartenAMPEnergyCherry-QtACzJvoGLjV7baP',
        'HardDreamyMilkRuleFive-1HqkB9C9ccszgUMC',
        'SpotlessAcceptableLionDancingBanana-2IvjUPPoasjB3Psa',
        'HorribleAdventurousRavenPeteZaroll-sbI3t7oKgy_beI_h',
        'LachrymoseTardyPuddingDoritosChip-FrBrXz-wnWcIXgbD',
        'CourteousVastDragonfruitDatSheffy-aMnD1QIF9SoSiQwQ',
        'HeadstrongOnerousParrotDogFace-Pzk4pAjq0Ws-AuY5',
        'TangibleTalentedPonyRalpherZ-TENdUqv0CL1FhKPq',
        // Episode 2
        'KawaiiEnchantingClintDeIlluminati-CtVitmcX5PxkPojz',
        'TransparentBoredHamsterFunRun-oUCKYudFhRsGC6cB',
        'BoldRudeCheesecakeJonCarnage-eqQTB1K5_aHc2hHn',
        'SeductiveCleverPigAMPTropPunch-Z2V4PkrK_mGXmsN0',
        'ArborealPeacefulZebraSpicyBoy-E_mCesApy4766iRo',
        'PiliableBlazingTomatoAMPTropPunch-gizvB689hU74zqOh',
        'SparklingCovertSwallowSeemsGood-WKQomIHiUqmS76xu',
        'UnusualViscousJalapenoDxCat-Yb4Bs4UEKa_kYhWQ',
        // Episode 3
        'MuddyTenderChowderGrammarKing-DhpWCkO1YYbD2ktG',
        'BlindingSpineyArugulaNerfBlueBlaster-XhmWQJEyG_VnWXca',
        'CuriousSneakyPterodactylEagleEye-_tNUZyR1PGZWsyTF',
        'ModernCooperativeDumplingsRalpherZ-aRB5GaMZBA2fIoti',
        'GeniusFurtiveSparrowRedCoat-lWR5nEZEdwUlDiVx',
        'SuaveExuberantDonutItsBoshyTime-JztkICSXZb589SrN',
        'RenownedWittyVanillaPJSalt-6WCURajzS_AuUjvw',
        'LittleGeniusGarbagePMSTwin-08tpWz10gWvTis-y',
        'CredulousYummyHamPartyTime-iJzaT0DvAh3aUmPp',
        'EntertainingDeafCrabsYouDontSay-xtPD-UPufRlb0Wus',
        'AntsyThoughtfulDiscSSSsss-kXiWTMseykD53Gc_',
        'PrettyInterestingCoyoteKappaPride-neXiGp39m6znQvPq',
        'ShinyUglySpiderPartyTime-jtK5Rw_GOE87AqYD',
        'PhilanthropicAstuteRamenMau5-iHpoNwR2ay55Rt6f',
        'TenuousCrowdedCarrotEagleEye-t-gy-2ht4QyEN9S3',
        'FastSwissSpindleSoonerLater-nz8QSt7IrTVjmR4j',
        'BlushingRudeLeopardDatSheffy-zVzLV96z4iJLcGbs',
        'SnappyShakingDeerHassaanChop-1CbBdTGMVID2kcK8',
        // Episode 4
        'ThirstyTalentedCiderHassanChop-O9ANf8uGedEfC4gn',
        'LazyEasyYamNinjaGrumpy-UD-vjxILeuSYEUnb',
        'TrustworthyAgreeableClipsdadDerp-SnIk_VNcajkw8qqD',
        'ExpensiveHeartlessEelPogChamp-hH_6bG2XFQaXpTr_',
        'GlamorousPlainGarlicSpicyBoy-dCCgf0KdQCCA5vfp',
        'SwissTangiblePanOhMyDog-of8PtewY5xs0k14k',
        'DifferentPeacefulGrasshopperGrammarKing-dFvpEBvzZRX22aYi',
        'KitschySolidHorseAMPTropPunch-bBp1xVsm1XgmXd7e',
        'EphemeralWonderfulPterodactylPipeHype-kQDnPcXnU9ZYXnbm',
        'LightObeseChimpanzeeJebaited-dVimA5iCjWPROneg',
        'OptimisticSaltyMageUnSane-hbz6i-p6SOLPUZm_',
        'RamshackleVainSowWTRuck-P1KLDht79Zp2VzD4',
        'PoorSmallWombatBigBrother-PZv10lEgbzYP4Ivo',
        'PlausibleAgileMetalDerp-uwRJX5qZ3ov9qWrQ',
        'CuteSuccessfulCrabsEleGiggle-XunRXm9dgCXoJzO_',
        'MagnificentDelightfulCheesecakeHeyGirl-8dv3cmEizdwS8zS2',
        'DirtyDifficultBearBCWarrior-6nhMG9EOeFqm9y75',
        'PluckyBoxyMelonVoHiYo-Jx-MqEelxXy6HXaO',
        'PeacefulTenuousPhonePJSugar-VVYwLi24I_zmHwOU',
        'GoldenTangentialPassionfruitChefFrank-XNTCvR4idRnxVTMb',
        'EnchantingTallArtichokeKAPOW-5qaxCLnKEoDvGMye',
        'BumblingAffluentPelicanWholeWheat-I9ThAX3bJ98QpDob',
        'EnergeticAmericanBillSSSsss-bS6G979TVzzhVzyE',
        'CooperativeMoldyWrenchSuperVinlin-6sNe7pVEsMj28XRw',
        'AmericanFragileStarYee-rRhitio2lORaJRTx',
        'UglyAwkwardPheasantSmoocherZ-A0qQYHlawSjYqtba',
        // Episode 5
        'BashfulEnticingDogHeyGirl-WEFlAqtJUIZfp_oq',
        'AnimatedGenerousCatLitty-Lp5bHStot4BmMgpx',
        'BeautifulSpikyPotDerp-zFf0g2ST16KVvz2f',
        'HumbleHonestCaterpillarPanicBasket-7uSaGMZLuiC6oA6A',
        'BadThirstyPepperoniStinkyCheese-N0jJ3nHB9opNZpJI',
        // Episode 6
        'PuzzledDependablePlumageCharlieBitMe-HjUtTcu4L0mlmlob',
        'FaithfulBravePhoneBIRB-iEkIYRAvYMnQnPfU',
        'BombasticAbrasivePastaRaccAttack-o9ireLA9xruq8Cxb',
        'PeppyEasyVampirePeoplesChamp-KOT5IZvfnLfhPrP7',
        'EsteemedEnjoyableEmuOpieOP-bTukpp5c6YWu4grG',
        'JollyMistySnakeAliens-lUjpfwNh0wlbQ-2l',
        'GlamorousLittleMonitorRaccAttack-ax0rXaIRw-I5vE-d',
        'CrowdedTrappedJaguarThunBeast-BipF3ItjVq1-VkQ8',
        'TameNiceDumplingsCeilingCat-4MUy5kRPEGeOOnID',

        // folge 7
        'UnsightlyRamshackleMarjoramBuddhaBar-V3AcDpnigmjtLy6f',
        'FunnyMoldyHerdHeyGuys-eynaD3XdSBrSG6DF',
        'RoughProductiveSkirretPRChase-kAzJ5fUYznnYQDTk',
        'TenderAmazonianMallardSeemsGood-OoClJvGqSNt-Ne65',
        'SavoryObliqueWerewolfNomNom-kl8yTEi0BgBmGLNZ',
        'ImpossibleClumsyLlamaGrammarKing-hK9aS1jyZ9HPZZoa',
        'KindWonderfulSushiWTRuck-244OMryliWqgIctn',
        'EnchantingIcyGrasshopperShazBotstix-3cQsfsWX3la04YVh',
        'ProductiveTenderBananaMrDestructoid-pOYga5pH_nrD95CR',
        'HardJoyousPheasantDendiFace-a5XF6hw10ZkR6NPa',
        'StrangeManlyVelociraptorCopyThis-5sOFivLpUCUp2OOi',
        'SullenEmpathicCrocodileSoBayed-FQOqvPZJAOBESwAs',
        'GorgeousProudButterflyArgieB8-FeM6rwkS7gSWyqox',
        'TransparentEndearingSwallowBabyRage-3WGnYHfvaLvU-kdL',
        'StrangeLuckyFriesPrimeMe-m2yqy-jnCsASvYOP',

        // episode 8
        'CleverAltruisticDaikonOptimizePrime-edG8Tp8CVJuvUPH4',
        'ManlyCredulousJalapenoBrainSlug-iTIvSFzrqEXHVakf',
        'SingleBillowingVampireSeemsGood-V4AKPQ8E-xJ74922',
        'EntertainingBlightedSowUnSane-h-UhLRYs6HjJ5H0x',
        'SparklyFaithfulRedpandaWOOP-gNNGtkWClUhcAvVV',
        'MiniatureEnchantingMosquitoPeteZaroll-IAGFB-DdK_kRUhqX',
        'FancyGlutenFreeTruffleCharlieBitMe-WJILJCqvgBV2welP',

        // episode 9
        'GiantBloodyDragonflyChefFrank-K8_l4RwTeUx2G53i',
        'GracefulSwissHamsterSoonerLater-1Z4i2Oeani8pD-mz',
        'PleasantProductiveHummingbirdRuleFive-6MUxGIi6RZ0Wu4XV',
        'HonestRelievedPterodactylBabyRage-1O9Cv7yPScVUVGhv',
        'BlazingFrailKeyboardNotLikeThis-4bc-qQypRh5qBtwJ',
        'ProtectiveWiseChickpeaTF2John-40fXM2FjdG0dTuy_',
        'PerfectCharmingOwlYee-eQ3SQvcY2tkl1Yf2',
        'AliveArborealEmuPhilosoraptor-AE7ooVFASJYWtaDe',
        'SuccessfulInterestingYamBloodTrail-YmCHoFqnh06kloZY',
        'RespectfulYawningBunnyDerp-So7xBG-DMeVgIYDk',
        'RamshackleSneakyQuailBigBrother-z95UN4gNMFcp8bzI',
        'VivaciousMistyWalrusMau5-qcT1KcK1Low6-lVe',
        'HeadstrongRoughIcecreamOptimizePrime-q4smz1qwrPMF07eU',
        'OriginalFaithfulKalePeteZaroll-MUi3EXnObdmLOSoK',
        'SleepyVibrantNuggetsKevinTurtle-xl3uYgs47rWrFhYv',
        'SassyDiligentPeafowlMingLee-C5bcqRv5wtVmiOcv',
        'ProudSpikySamosaSoBayed-wTsJezq2J_ztE-0_',
        'SweetFreezingDeerBlargNaut-KkTmaF27-Me-dhMK',
        'AntsyDoubtfulDragonAliens-YOecCllvtiq-4AhZ',
        'AthleticRichBulgogiRalpherZ-vtdMAOpAaSer5ISv',
        'FaintPricklyEagleFeelsBadMan-n0nskTV1HM2JWf0w',
        'WimpyConcernedDuckPogChamp-vvGnlhcNuhAX2JPv',
        'HardSmoggyDumplingsPanicBasket-SCtvrbszILHc8wzN',

        // episode 10
        'BlindingShyPuppyCmonBruh-F4thsgP_ytf1Xo0A',
        'EagerDeafLeopardFUNgineer-gi4_n6GwlkxnEVGE',
        'PlumpMotionlessDogeHumbleLife-3aZpiyTgEj3rPTr4',
        'VenomousAlertAmazonStinkyCheese-OXpSVa21QM-AR63f',
        'OilyColorfulBatteryPanicBasket-wushTMpQFigfbZv9',
        'BoldIntelligentDunlinChefFrank-UJ6jiG70ecf5dpnq',
        'AmericanCreativeFennelBleedPurple-mREz08Z_4xm2sMUU',
        'LitigiousColdGoshawkDuDudu-xiU9_SnlsqIBKieg',
        'HilariousColdbloodedCodWholeWheat-o8NL7tUyYmWAQy9z',
        'AmazingInquisitiveKoupreyMikeHogu-ydE4WTaDyefHVisg',
        'SpookyMushyMeerkatAsianGlow-LjX-cAoqNq_MHmt5',
        'DarkShyMeatloafDxAbomb-WrXtEGHZzMA-mrI5',
        'SarcasticMuddyCurlewYouDontSay-5Xhyz9FF17EjBJsc',
        'StupidClearSquidFailFish-38bfXwyq8HPSSUiX',

        // episode 11
        'DignifiedDifficultElephantRickroll-1gJND1KoEPX9CcHv',
        'BlindingBlushingJellyfishAMPEnergy-bOxvltfjG2FxXWoP',
        'MuddyAcceptableFishNomNom-uBYxrH39Sg1K0EoA',
        'CrackyMotionlessEyeballVoHiYo-twTdwtwQsLOmcFUx',
        'SleepyIncredulousPidgeonNinjaGrumpy-zu3XeqopfYPaRRjC',
        'FantasticSpotlessStarlingAMPTropPunch-qFXP-YYsbaVLHK20',
        'TardySpeedyCiderTBTacoRight-vOPZQ6aIqDxyFBDk',
        'BelovedDarlingGoldfishDatBoi-xIK_cA38wZwgHi9L',
        'SpotlessAbnegateStorkDeIlluminati-zRDmQ_tdi7x9OkWL',
        'CooperativeFastWalrusFutureMan-PomGmQ2yEZjvlLbL',

        // episode 12
        'DaintyTangibleArugulaBCouch-QWiA3vX1dtMSkQ9f',
        'SolidFamousFalconMoreCowbell-TXIcVfSEgNRTa-Td',
        'DaintySparklyLasagnaPeoplesChamp-A8CoIOzuOZjcUalt',
        'WildPlainDuckAliens-7KxNxh2lsp6NdacG',
        'AbstruseTenderAlbatrossWOOP-1q5hqx10QNQjL-br',
        'DaintyHeartlessMelonYouWHY-EQYVHdb5ycIu3cX5',
        'SpotlessEmpathicCockroachDancingBanana-G1M0SQG0LK56wupR',
        'AggressivePolishedBadgerPunchTrees-NqvASoxGcqof5tSW',
        'AbstrusePricklyDogeDxCat-xp-X46Y2bzSvE_yb',
        'PeacefulOilyGaragePrimeMe-9blCLXb2eyvldiUg',
        'SourSmellyOkapiNononoCat-tq5uykv5PfXC_C3W',
        'RelentlessBumblingPieCorgiDerp-jnjpdNbtIKSRXTCV',
        'IncredulousCulturedPastaCharlietheUnicorn-AJpA2wvtK-3dyHaN',
        'ResoluteRichCaribouRlyTho-SiDCLpbsz0A88sQX',
        'GorgeousSpotlessCodPhilosoraptor-OGwkGRFv3EXyFx8T',
        'UgliestAwkwardCurlewBatChest-iVnqUuUuS16jNe82',

        // episode 13

        // openEnding
        'GentleStormyWolverinePJSalt-5brkW-dDeuNO9Pol',
        'EnthusiasticShinyLapwingTBCheesePull-Rirk7SP-uLRb8OpM',
        'GentleCarefulBobaStoneLightning-aEDFutJLhiONMi2R',
        'BlatantProudSheepNomNom-GO7jn-s5hLOLsThK',
        'RamshacklePiliableChimpanzeeVoteYea-aLNHniGMIY8OE8R9',
        'AgreeableHealthyKoupreyNomNom-N-X8_PNHbm6tpW3w',
        'IntelligentBraveClipzUnSane-M-GfDPWQQcM9G-gs',
        'TenderObservantMetalUnSane-hB-Vq06DaURSJ7BO',
        'BetterNurturingTubersStoneLightning-wOyPdt5mXImCV5i1',
        'ExquisiteCrunchyHerring4Head-0J7djdKGHwPy-JCm',
        'AntsyBlightedCurryRlyTho-XTdbL3wGr4adkowF',
        'CarelessBelovedPonyPanicBasket-J6EoXGkKnUK-9dg-',
        'KnottyHappyEagleDancingBanana--Ce1kSVHBz2f1jgK',
        'SourImportantMagpieTF2John-p23V4cxGMyhxM0DL',
        'SecretiveGoodOcelotWTRuck-aBUqvZHAQMYnKgE9',
        'PunchyRefinedSnailFailFish-eRtOA2vlOFDq6lfh',
        'GenerousHedonisticMartenTBCheesePull-ffVl_GJ8OYo0IqiX',
        'DepressedYummyBeanCopyThis-qcY3fpqLMJfd-5Tm',
        'AgreeableSnappyLatteFrankerZ-HkFZmHR1JJyrDLmo',
        'HotHomelyBeanAliens-ZYKljsFPm6me5ZNI',
        'PopularBlazingDunlinGivePLZ-suzoh2NmToBTfn-I',
    ];

    protected const array Episodes = [
        [
            'user_id' => 0,
            'title' => 'Episode 1',
            'slug' => 'episode-1',
            'youtube_url' => 'https://www.youtube.com/watch?v=D9PHIxhU_MM',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-01-16 16:00:00',
            'clips' => [
                'StupidHumbleBeeResidentSleeper-nP9QXjKx26XY9k_D',
                'SoftTemperedDeerSmoocherZ-Pg5m0Sz5AdCAUJWO',
                'PlausibleSavorySwordCurseLit-y9LZMS1ERrSSq4N4',
                'PunchyWanderingDootImGlitch-pRyUHeGFUXT9vr3U',
                'CooperativeAmericanPheasantMingLee-5FXZZ91UFu9b-8T3',
                'AttractiveEvilWrenImGlitch-duvV8mJIFIq4C1QT',
                'EasyIronicSharkSaltBae-YoQgrQCxYcGoKwFd',
                'VastMushyElkKappaWealth-UvFk5M20T1-uNIee',
                'ShinyColdbloodedMageCeilingCat-M9KaMexmbCUdXvW4',
                'CreativeApatheticAlpacaM4xHeh-vtAnNPvrgXYZPJTS',
                'CharmingSquareLyrebirdCoolStoryBob-Di5d7-2Ju-O_0VWW',
                'FaintBoringButterSuperVinlin-PcB6n7v1YFpgvpSe',
                'SmellyGorgeousIguanaThunBeast-QCwJQNN9fAO9o9RM',
                'GlamorousImpartialClipzTTours-ZU8SbZn5ZEGHbRV4',
                'CleverKnottyUdonPRChase-N_zw9BP7soQFegFG',
                'BelovedPowerfulHumanVoteYea-JA2ieqE2dTp7Bfdw',
                'ClearDeadWatermelonHassaanChop-bWWVSUUvMXNAbTd3',
                'BoxyFineBorkMrDestructoid-Nz0rwTv3eXGtUM0n',
                'CalmKathishParrotTF2John-4ZpmI1AfPQoEsd_R',
                'IgnorantMuddyLocustAMPEnergy-VUBWoHLFCEteN3C_',
                'HelplessEagerTardigradeSaltBae-LKKuYwxmKhbOgD1G',
                'DeadKindDadUnSane-bRoTdW1iy5ZwuWsN',
                'GrotesqueSpicyFoxHassanChop-Np4vO_C33mjI7G5b',
                'InexpensiveResilientAppleOSkomodo-sbNBVHuO8fDaMmtn',
                'BovineWittyPepperoniSuperVinlin-S1ETPMeUJrPoRoYV',
                'CulturedAverageWerewolfCharlieBitMe-5SdXIxXzpiI9Qt2y',
                'ExpensiveCrunchyElephantKappaClaus-aN4xFHHxAPyUOnM9',
                'InspiringAnnoyingPigOMGScoots-MkuSyJ9cYFx1kCtA',
                'LuckyPrettyWrenchTBTacoLeft-GzKmEqva9LLHVHVs',
                'ScrumptiousDaintyCocoaBrokeBack-nZJf9zZ-OAIc6LS6',
                'WanderingImportantBasenjiBigBrother-ba-JFKyDNodYdOWH',
                'HealthyConcernedSwallowUnSane-EeJIsA8ePcjGi62v',
                'SavoryTangibleNigiriVoHiYo-3y-dv8tbBQgLWYvZ',
                'GentleNimblePanFreakinStinkin-1eErSWrf0oTe4DNb',
                'FamousAltruisticCucumberSaltBae-jMssVVE4G8F1DOWz',
                'TiredPreciousMartenKappaWealth-zFzxz3qlrQYGOWS3',
                'AmericanSecretiveChipmunkCoolCat-y5MA7WfJuezTJ6le',
                'PatientDifficultSpiderDerp-3XSJ5Sy9MSFPvcac',
                'FrozenSeductiveSoybeanTBTacoLeft-68OrgaC-HEgyXI2_',
                'CrepuscularHelpfulWaspVoHiYo-x1qSTRXwuhnCsoV4',
                'SpotlessFaintClipsmomPartyTime-iVeYirUOukt2MMqK',
            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 2',
            'slug' => 'episode-2',
            'youtube_url' => 'https://www.youtube.com/watch?v=2tQbOkXfdGc',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-01-23 16:00:00',
            'clips' => [
                'SarcasticBlightedSangPRChase-iwD6ZpLo6KNnt279',
                'NeighborlySparklingRaisinPeoplesChamp-wTnyIx7hMs_ZI8YY',
                'SillyCreativePlumageStoneLightning-6HYMKhnGQx7Qp9ht',
                'MuddySlickChimpanzeeJebaited-CeEAhbA410rFqmDL',
                'TangibleBetterHorseradishThisIsSparta-Pwo4iY6ud5njguhv',
                'CulturedMiniatureBubbleteaVoteNay-x5JgfuLHQwtYx5Qh',
                'SaltyBovinePrariedogAliens-b10f7yJI_ijIJJh-',
                'SparklyDeterminedVanillaUWot-WS3svdoabNb12QGm',
                'VibrantEphemeralQuailMrDestructoid-o_1ixWnAdkB7jDWH',
                'OriginalSarcasticLaptopHeyGirl-SaGymc43jgUACVnV',
                'MotionlessCloudyLegTinyFace-B8sJIwc8G49VNnkR',
                'GrotesqueStupidSnoodWholeWheat-Qc4jPte4HUOp-2dX',
                'BenevolentImportantOysterVoteYea-bMXRDYEDki7USUIZ',
                'LazyIntelligentFennelNotATK-sBs1Tln-4tZKGK4J',
                'DepressedPlausibleTomatoKreygasm-1NEsfCaFaWk4HCuc',
                'SpineyCrunchyFriesOMGScoots-sS7QVVGAHK5Sxa4Q',
                'SweetAgileTarsierOSsloth-RM6QEHEJ1TGUuXHE',
                'AmusedCautiousAxeMikeHogu-X0Dk8hcCAMFKaiR_',
                'DeliciousAbrasiveOstrichOhMyDog-DoRvCFstZ3PY9Nl2',
                'TastyMoldyPheasantMingLee-oxjvdI7OpTMj_BxN',
                'KathishOilyBottleTooSpicy-1Thwa6Is8VH82eqh',
                'ConfidentTrustworthyToothBabyRage-amBLhsBrzjHpgL2-',
                'HelpfulFlaccidWolfLeeroyJenkins-F7Bp_fEc8Dvv0c8k',
                'TamePopularJalapenoPrimeMe-onoMzK-aqVqlGAdt',
                'MoldyTolerantPeppermintCoolStoryBro-u4ZMYFl6vahmQD1V',
                'ChillyRealFishDBstyle-PFpjB4JV3VH5-GSG',
                'PerfectCallousApeNotLikeThis-FmdLIDFMAJ4Rjze5',
                'HyperBusyPenguinUnSane-R6nZS_PRE57qp_py',
                'SplendidImpossibleKuduLitty-Oa0BwA37orawprrN',
                'ImportantIntelligentParrotHassanChop-xglTuLCPxtVjHBDM',
                'ShortWittyMangoWOOP-QZeZj9AVcvUdYOfW',
                'HilariousAntsyDonkeyNerfRedBlaster-FEINwuAhhUrBur3l',
                'FurryMoistSkirretTooSpicy-eTWeXugYLK385YVc',
                'FriendlyHeadstrongBillGOWSkull-hYvbWd2hdoVtoeMR',
                'DignifiedHappyFennelGingerPower-G1R4wu6DxjZ4sKBm',
                'BusyEnticingPonyTheTarFu-S1t8cOA_gE2Vtb9W',
                'FairEmpathicLaptopOhMyDog-LkjlqxgRzwflZ4wm',
                'DarkDeadLyrebirdYee-yTjGwJRT9qkc3YR5',
                'SwissCourteousBaconTBTacoRight-Aaz5mLHUOoPTQSPX',
                'ShakingStrangeAdminWutFace-6VNLFSas71V71QXF',
                'TastyAntsyCookieEagleEye-QoE9GHi-zgDTD8jh',
                'FrailImpossibleJellyfishDancingBaby-zO5_xSX-bOdq_Ftt',
                'TalentedShyGarageMVGame-keqU8I7XJ5FI1G34',
                'YawningEnticingDragonfruitItsBoshyTime-XRA3St7AI1k49hML',
                'SuccessfulResourcefulPlumPartyTime-iPGxDnmhkiYcc1p7',
                'AverageAgilePancakeKevinTurtle-MI4eLE8P2oPOsoKs',
                'GenerousBoxySwanFloof-HM_jprvcQDR7WnwR',
            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 3',
            'slug' => 'episode-3',
            'youtube_url' => 'https://www.youtube.com/watch?v=-BX7qzTCt3U',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-01-30 16:00:00',
            'clips' => [
                'WittySassyCroissantPoooound-dnh0LrXD_Ub4Q9dQ',
                'OptimisticPolishedZebraDansGame-JbwNl0XK-70cnKs6',
                'CoyIncredulousGooseStrawBeary-G4b9M0wpGKE-ekfc',
                'EndearingNastyOxKippa-6ZQBCAFPhNzCFQl7',
                'BitterKitschyFiddleheadsPeoplesChamp-aiT5GANb5ebo3czb',
                'FunOptimisticTrollPRChase-36HigJphxyYhwww8',
                'WonderfulOddVultureYee-mUHZx-F8CJl7j32b',
                'EmpathicInterestingTermiteNotLikeThis-t14_6HDIkIfFRyrn',
                'JoyousKindPangolinAMPEnergy-SqtiEytiqGMHRArD',
                'OptimisticMiniatureChickpeaHassanChop-qS0zkmYczWSYAAwU',
                'GoodCallousMonkeyAMPEnergyCherry-wFg-XUTexcqt8SIQ',
                'KnottyArborealYakinikuFeelsBadMan-MaoUkRfna03-a_v1',
                'SquareCreativeClamNerfBlueBlaster-B5sf3Kvk63eWJwuv',
                'SwissKnottyLousePoooound-bAh3WUe1pXUWTync',
                'AnimatedGoldenLaptopRitzMitz-DKPrbIj7lJzFyyK7',
                'BreakableAnnoyingBobaTheTarFu-gm8il_EIarJvyUvc',
                'BlushingWimpyCasetteDatBoi-urxkRPureBgccey_',
                'ArtsyTenaciousMoonBrainSlug-XmjMhrMW_XzI0Kyb',
                'PiercingEsteemedLardMrDestructoid-O8NlVDOif2rUhCDo',
                'MushySpineyJackalOSfrog-f6ORyCUEJ0tclaYa',
                'BrightZealousCodAliens-0DU5tTVQKVjQB9xV',
                'FrailClumsyDadAMPEnergy-GxadwZ61U6xsxmN9',
                'OptimisticTangibleDogeUWot-TjkhPnsbdskziBI1',
                'CoweringPlausibleSalamanderAMPEnergyCherry-Noqh0qaHBANyHazb',
                'OutstandingCrispyChimpanzeeGivePLZ-a-XNZqlb-gQ_aXLG',
                'HappySuaveWatercressFUNgineer-aZqh0TxfbZjTrsDj',
                'ObliviousScaryKathyBibleThump-9P0tCp2svNC70VxG',
                'SullenBrightCobraGivePLZ-5saN78vW9W0MvqlS',
                'DrabInventiveBibimbapTakeNRG-HlGljvlNFuySqlIY',
                'SuccessfulArborealBaboonKAPOW-o7-YESrsTJvlBcU-',
                'SpikyTangibleDotterelAliens-Ywzv0-w6uCeg2UH5',
                'BraveBumblingMonkeyJKanStyle-ujWXzs-Jz1bc73kQ',
                'BoredFitEyeballPraiseIt-cDvHV09Ba5tSB6Hb',
                'StylishImpartialOrcaHeyGuys-lmObfR7X38JtQMW4',
                'ObedientGiftedPhoneHassaanChop-JojRk22BBuvSKC9T',
                'ThirstyCallousPieBlargNaut-c1Pa2-CKdlsGmMtT',
                'MuddyConcernedGerbilPJSugar-q4VK_xoSKRGaVRUs',
                'ClearDelightfulEggCclamChamp-9pe64XifCPUUwAOf',
                'TalentedSpicyAlbatrossNinjaGrumpy-DLzVtz7H4r9R1qMJ',
                'SplendidPiercingPuddingArsonNoSexy-OMj5X6TA1lxCedfq',
                'LovelyEndearingPenguinArgieB8-cLQ2v0eRxnsAWp9Y',
            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 4',
            'slug' => 'episode-4',
            'youtube_url' => 'https://www.youtube.com/watch?v=AC9bdrzWiOo',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-02-06 16:00:00',
            'clips' => [
                'SweetHomelyChoughJKanStyle-27iiaAUv5PIYmNXe',
                'TawdryHardFriseeBudBlast-VlaBIgZThOHrcmSi',
                'EncouragingKindHornetMcaT-Xid-73s0LspQQA3L',
                'KathishHomelyCrowPlanking-SCM-bL7CgQkc24ID',
                'CrowdedSpunkyDotterelDerp-0hf71PHgrZlvg0w-',
                'AnimatedRoughTapirJonCarnage-3LsA-0wcV8jH42mi',
                'AdventurousLivelyBearCeilingCat-k7AcO3476q5gSlGn',
                'PoliteThankfulCrabAsianGlow-f8MWSZp93alqkU3i',
                'ClearSlickOxArgieB8-mRQVHijMFYaicXND',
                'ResilientHeadstrongGrouseJebaited-sX4VApYf7ozG-Hap',
                'CrowdedBlitheTrollPJSugar-XNe8cZe872riPg-p',
                'DeterminedRichChickpeaCoolCat-jttXk3pwqwTUDwV7',
                'SmellyFrailDelicataGivePLZ-QDmKaDwuKuJtZJf3',
                'EsteemedDreamyAlmondKeepo-LYNWtJx1AgphG-42',
                'LivelyDiligentGorillaJKanStyle-9sW9dY5oPvOYuMNO',
                'EncouragingHelpfulFishBibleThump-oqs0OvKSSrAGrbmB',
                'HumbleWonderfulFerretM4xHeh-gfSzPjyNlXRKM-0G',
                'CautiousMoldyDragonfruitPanicBasket-XcBV8v-OgnxxAdI4',
                'PunchyBitterChipmunkDoritosChip-O8oX32lAmvKfG3Xk',
                'BraveShakingAlpacaSSSsss-Jy1XiZAxrOGLd_l9',
                'ZealousSmallMomKeyboardCat-AYdvTTavJ8TEd3pr',
                'TameSmoothWasabiChefFrank-8Hf60aMnPxSU5QX1',
                'InquisitiveArbitraryChickpeaOSkomodo-F9g_YYkrPzcjBxQN',
                'BlushingFrailSheepPunchTrees-F1LdWe_JXV8Cj9PE',
                'FlirtyHedonisticLaptopLeeroyJenkins-XsWdnPktoBbvrLVW',
                'AgreeableLazyChickpeaPermaSmug-LRVNuz-DccaV54b3',
                'TawdryAnnoyingPrariedogJKanStyle-tOedvV4J16uvjmDM',
                'TallFantasticSnailLitFam-A-lhkcyXhTRpKv-M',
                'ShortCorrectCheeseKappaRoss-nj7SCUvFm4SqgPFr',
                'TrustworthyPlayfulMagpieKippa-zfvCFt-4rfwdZPdv',
                'SinglePlumpCatKAPOW-naHcPLEC2kxrnNxb',
                'BetterStupidYogurtPhilosoraptor-SoFVyYpR5EOEi466',
                'SincereThankfulKoupreyMoreCowbell-rqWUMhL9asACRPji',
                'SingleTriangularPidgeonBrainSlug-zA4Kp-BckWCNqv24',
                'AnimatedNiceLardPrimeMe-jLAxTci8xutSXnuv',
                'CooperativePricklyGooseSaltBae-v9qjwG25wYFn0n3q',
                'MoralIntelligentNostrilItsBoshyTime-8R-3k_p4qGJKH_Y1',
                'SnappyDeafOtterNerfBlueBlaster-sVQlgo7dBc-aDb3d',
                'SuaveWanderingSlothPipeHype-l980bWzBr58WAfyD',
            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 5',
            'slug' => 'episode-5',
            'youtube_url' => 'https://www.youtube.com/watch?v=jvuk243L8z4',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-02-13 16:00:00',
            'clips' => [
                'BlushingProductiveNikudonDoubleRainbow-_HBL_ULg-G4xiKXx',
                'CarelessDullOrangeEleGiggle-ZEpTZ0eTJy3hO_Di',
                'HardZanyButterflyDerp-hNw2oGqAUecSsKmY',
                'HeartlessInquisitiveSandstormCclamChamp-oAqWhb6bG08H3QG2',
                'PoliteGrotesqueWasabiYouWHY-igQgMRUbKr6xwu6d',
                'ArtisticHandsomeNightingaleMrDestructoid-M0Ee2o2KEmXchsRO',
                'SpeedyCarefulFinchPJSugar-vu5thW7trthlGLmh',
                'TenaciousAstuteTeaTriHard-Earv5baovT2GEgU6',
                'SoftTolerantFlyLeeroyJenkins-Ky_gnEC0m-vqwgmF',
                'PlumpEasyBeanCoolStoryBob-ieWXP9YUqdMbKedt',
                'ImpartialCrispyYamPartyTime-HXXWk0ELpQH2-nHC',
                'IcyGleamingCucumberKeyboardCat-9m3T8q-AwMSWUBMh',
                'QuaintEnergeticSkirretBleedPurple-NIuoKf7Ogrx_oUwo',
                'DepressedLivelyRutabagaWTRuck-Az3AEfecJJge5UeY',
                'SuccessfulConsideratePorcupineWholeWheat-cjDlwC3cEH-xWLpx',
                'NaiveSuspiciousCucumberHassaanChop-bgvd2rVUvrcjn7P-',
                'GoodSinglePeachRickroll-y2G1CsUBLsV-62zC',
                'SteamyBillowingNarwhalThisIsSparta-Nt0_pyBIZ7UNe9fS',
                'ExquisitePeacefulElephantVoHiYo-MexS3jZ5GpfsM95_',
                'CourteousSourSalsifyHassanChop-pOClTvFPH1ybKAi0',
                'DifferentSpikyLlamaTheTarFu-UK8RRfYhb_A2XFpQ',
                'PerfectAntsyScorpionPartyTime-a5IoajGm7muZeQiM',
                'AcceptableBlightedOryxPicoMause-Hk7iYPlgshqQAyyf',
                'AliveIronicSheepDancingBanana-5tSYgNh_7S5x58mh',
                'DistinctCooperativeOkapiImGlitch-og2-CvYwYMYGDVWv',
                'GorgeousPiercingKiwiBIRB-Zw2r1WoSnfrqtWG3',
                'StrangePlacidGiraffeDxAbomb-u9nQKeTXrnnwbUU8',
                'PluckyPrettyLobsterHassanChop-kHM3uJJ7q79uqOOZ',
                'PrettyAmazingMochaRalpherZ-3jvM5cgcwxiec6hs',
                'ModernOutstandingMonkeyCurseLit-3h5mnLd7sZJJDMLN',
                'HealthyDistinctGalagoShadyLulu-IfdAv852nQmdVuKZ',
                'FaintFragileRaccoonStoneLightning-hvofOmPssdMod6aR',
                'DeliciousEnergeticZucchiniPJSalt-D_6dc9fkfgTi6tsS',
                'BeautifulPiliableTubersPupper-W-tYmUe0II7QmGU1',
                'TenuousSparklingWeaselBCWarrior-Pu9ggzbJZxDEd8wd',
                'SpunkyCulturedWasabiSwiftRage-EkCDH401E6AmugzV',
                'TallPreciousMuleDatSheffy-iCERvDNtgryrJv-r',
                'SmoothBlitheDogeGOWSkull-EQtQGXmjnIRV7uho',
                'ColdOptimisticGullRlyTho--5xmA5Bs_CGFYBSu',
                'TiredObeseTermiteMingLee-etWvZnM-e4jQFBvp',
                'IntelligentRefinedKeyboardCoolStoryBro-iNW1LXlr8a_fQbfp',
                'SpotlessVastMosquitoANELE-KjIE1q5nR2exBqRO',
                'SuaveSuccessfulHippoTooSpicy-EGC-fUu-NuzsOJyb',
                'AbnegateSlipperyBulgogiUnSane-uWS1v7mESK2e_6MQ',
                'GenerousTemperedRamenBudBlast-RTVHu1SXRYzMn87k',
            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 6',
            'slug' => 'episode-6',
            'youtube_url' => 'https://www.youtube.com/watch?v=7QZH4rYSKVI',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-02-20 16:00:00',
            'clips' => [
                'MildPluckyFlyYouDontSay-q593sExs4GxEoRcz',
                'EmpathicCoweringCroissantEagleEye-wQ8LO6CYfaj4gExY',
                'SuspiciousIronicRhinocerosJonCarnage-xBwNgbHoISEW7wTS',
                'HealthyYawningClintmullinsHeyGirl-oZiNYq3z4zcURPeP',
                'CoySuccessfulSpiderTooSpicy-UiVreGYnOfOsNnn9',
                'StormyMistyPorcupineSMOrc-jX9S7pz1fezPaKy8',
                'RefinedJazzyStarlingJonCarnage-VJVqWbUGIAeu_heU',
                'BloodyMiniatureJuicePartyTime-oyalmZF13wWeK3Xq',
                'WittyDoubtfulOctopusSwiftRage-Ia7ZO4KAc2bgQU3_',
                'TemperedCleverPancakeMrDestructoid-0qZ-i_C71FNrylRU',
                'GloriousPoliteEchidnaPeteZaroll-WyvC8dNHB9g6Sumd',
                'ArborealTawdryApeFunRun-wH8ZeRe_z7EhFGIb',
                'LaconicEndearingKimchiDansGame--ys2b-0FNysKu7Mn',
                'RichDeadFinchSeemsGood-h7jgXiVb4h85-tcw',
                'RudeRepletePhonePJSalt-csVP-PFuuwSHyxxq',
                'InquisitiveLachrymoseAntEleGiggle-wr5kXCcIi_aJARUd',
                'AthleticToughNarwhalShazBotstix-lYkiURL_ATF6tG_d',
                'EasyBlatantMinkDatBoi-NIDmzDHM-dHDfR-A',
                'BumblingAbnegateGarbageDansGame-Bqt2dy08WYKLFQla',
                'AffluentLovelyTroutKlappa-5wlw4mwgJ3JYYp-d',
                'CleanFancyFishCoolStoryBro-nsU0XdAdEySbhCP_',
                'ProductiveLovelyDelicataOhMyDog-AzjvQ-6UczOO_-h0',
                'SpookyArtsyMarjoramThisIsSparta-EFUe_l-sq1ZkQgeA',
                'SplendidConsiderateIguanaCopyThis-9YufKX7t8iiqTyh-',
                'SourAssiduousBulgogiPlanking-VQNdQXNQqd5w9cJp',
                'PoisedSnappyBarracudaItsBoshyTime-HEuWSRrYhqnOdwZ7',
                'ResilientObliquePigeonItsBoshyTime-eJsZwQCwAMoBfpyx',
                'HumbleBrightSalsifyBlargNaut-l432OuHFIKJFWR68',
                'NaiveSpicyShieldFunRun-ZHh2vU_ozLcvu3FW',
                'RealGloriousCheetahBigBrother-M0k4McoSUC3ZAw4J',
                'TenaciousFancyCheeseRickroll-G8SMqDK7AYTL_Wuk',
                'HungryBlightedDootPMSTwin-ZgVfoVCOJhC11UHt',
                'FrigidDifficultShallotNerfBlueBlaster-qMPGa_Uxdi1gq2JW',
                'RichCallousJackalSSSsss-BB8A1RhOaknUDRqH',
            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 7',
            'slug' => 'episode-7',
            'youtube_url' => 'https://www.youtube.com/watch?v=UG98Ygvlzhg',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-02-27 16:00:00',
            'clips' => [
                'RenownedAggressivePoxOSsloth-5naxxLsMcY_gQrrW',
                'InventiveSpoopyGoldfishCoolStoryBro-IHwtAlunymgLsl2H',
                'UninterestedTransparentCasettePeteZaroll-4B0RW1XlRpO8ZkKJ',
                'FlaccidSullenLaptopArgieB8-R-YBkX6Z79TbvhWm',
                'HumbleBeautifulDonkeyWTRuck-erkw0B7uCo96mR0z',
                'DeafIcyAmazonJonCarnage-HNKpsG0CfnVHbo83',
                'ResoluteSuccessfulTildeCorgiDerp-oRD6i-fpyqSpW6rp',
                'TsundereNaiveEchidnaWTRuck-tMijRiUlY2gXIxRk',
                'CarefulPluckyLampDoritosChip-duMMsnj6QgM452Cj',
                'BoringPuzzledGiraffeOpieOP-3ORdDhR5F2vU4Nra',
                'DeadCleanCurlewTwitchRaid-yCGqhZAetV7b4n9a',
                'BillowingTacitBubbleteaRalpherZ-Gf3CFxFS6cNYSDvG',
                'ZanySquareEndiveEagleEye-QprkHuuVCLqFywm6',
                'SillyNastyMinkBrokeBack-TY3MShmhHpiwa2kv',
                'EndearingUnsightlyButterTwitchRPG--8EfhtYhrnMfr_Hw',
                'RelentlessInexpensiveWoodcockYouDontSay-watqyru0c_SUFu4y',
                'SilkyAstuteDoveThisIsSparta-gjKBVp2-Qn2KMU5y',
                'SecretiveSmellyElephantOhMyDog-FONl8DzU43cg0vGn',
                'DifficultFurtiveClipsmomCharlieBitMe-F8x-V9uTo9XpP2A5',
                'FurtiveProductiveNikudonLitty-E6RIGBPY6MajVdvs',
                'AmericanFunnyDugongTakeNRG-BrP4oLNbpvBXeEmS',
                'BlithePricklyPonyDoritosChip-C_mjC42LKOJVHFkx',
                'SlipperyCallousAsteriskHoneyBadger-Ih993Pbrme0Yxp1d',
                'BenevolentAbstemiousOrcaBrokeBack-_efVdJHmK0KCHYHB',
                'PiliableRoundPidgeonPeteZaroll-nV1qBW6IFhhjF473',
                'TubularSpeedyCheetahYouDontSay-47lMDONU419Ic8y4',
                'ShyEndearingWafflePupper-mM5X2QVQWSmeYNkd',
                'BlueSilkyPoxSpicyBoy-ESRLfBwBGvlZB-X4',
                'ScaryAbrasiveDadArsonNoSexy-v5iiWODKOgiv2pQv',
                'HomelyGlutenFreeNewtTTours-9fwx3EVfy97HWWV8',
                'PrettiestInspiringGarlicPeanutButterJellyTime-i7BgX4Pk6Bctd_qK',
                'HeadstrongAdorableKeyboardChefFrank-HF1dEi8Vl48ku9G4',
                'AmericanRudeTeaTinyFace-hTVT-gthooViMrYF',
                'DiligentScaryCarrotStrawBeary-e9Fg7YscjnUXe5kF',
                'FuriousPlacidCourgetteYouDontSay-rtWNoO3-7BRVH854',
                'FantasticDarkCroquetteCeilingCat-1ZzT-PqE8Mg-J_nC',
                'CloudySavoryPotShazBotstix-PlCdkshU0zMQpPqp',
                'ToughEnergeticClipsmomDoggo-WlZdlLFkPHHepnbR',
            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 8',
            'slug' => 'episode-8',
            'youtube_url' => 'https://www.youtube.com/watch?v=jmS9vue3XLY',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-03-06 16:00:00',
            'clips' => [
                'SmallImpossibleRaisinTinyFace-x8ZMoubPT5PtD2qw',
                'TallCrazyChickenTBTacoRight-4AY0kmUinFFw6Lsc',
                'CuriousObliviousKathyWutFace-XYHby8Zp2Zvcrc-G',
                'AntediluvianUnsightlyKimchiKappaWealth-uRvVzUsNDG8MYR0K',
                'ResourcefulClearSwanPeteZaroll-y1JONhmHuvkC1wdM',
                'SecretiveTriangularTurtleShadyLulu-arr3zS-rtDC5pumj',
                'SmellyBloodyPeanutEagleEye-Nm1UjzNSKF0YQko0',
                'SparklyPoorMangetoutPeanutButterJellyTime-AP1RmGLR2h1yqnuA',
                'TubularProudNuggetsDogFace-mfoc-_yPC1CaBA-Z',
                'EnticingLongNuggetsCurseLit-1LUi7d9JzNhMZ2Rx',
                'DreamySassyJackalChocolateRain-cKXGK-Q0pzFw19kY',
                'IncredulousAntsyGuanacoArsonNoSexy-EjqUNcmAqQwfpRhg',
                'OilySmoggyElkTwitchRaid-k12YxTEPL-jTDBgL',
                'AcceptableStormySaladKreygasm-F4fHj1YAWtM18ZpI',
                'DeterminedWittyEggplantKappaClaus-i6lhKvoXjXD5wVMh',
                'SpeedyGrotesqueWasabiPeanutButterJellyTime-ecDunFpiBi3bF9YJ',
                'SpunkyPoliteInternWutFace-bxZ_9lqwhcN6fNBg',
                'FrozenImportantSpaghettiChefFrank-kJu51kFooX_qkkUe',
                'DependableEnergeticDootVoteNay-Np_cOJztqnJBU7pb',
                'ApatheticGorgeousCardChocolateRain-qW6m95UrMX8JOoCg',
                'BigImpartialWalletAMPEnergy-8RYRjexnyvbeNfrV',
                'SmallBigEggplantKappaRoss-TkCIOg5k0HGgpMJw',
                'SpoopyBovineCrocodileVoteNay-0sG5ByX6omW8lrFQ',
                'TrappedConsiderateMeerkatUnSane-_ILmAxgH0TXF32Eg',
                'WanderingCulturedWoodpecker4Head-smZE8qTZA7h2tldn',
                'EnticingFitTitanMau5-JskmVguAHoB8PRTB',
                'ExuberantEnticingWitchHeyGuys-Wcv6qzZUhQ-mJX9n',
                'ColorfulFrailRutabagaDoritosChip-h5s7U_Jo0rp4H2dO',
                'ThoughtfulBumblingChamoisBrainSlug-lEHvQShgjaDktz52',
                'GiantInspiringAppleBibleThump-DdbKNxYqdiDomQDC',
                'UgliestHonorableParrotSuperVinlin-jOGrifsdMbWzNn3A',
                'NiceHomelySmoothieHeyGuys-mgKOicnKq0cr4A_O',
                'BlightedSavoryMeerkatBIRB-LSEP1jOaf7cWGgQT',
                'ImportantSpotlessStarlingFreakinStinkin-IbKyBsNxcjRI0DCC',
                'DignifiedColdbloodedSnailPicoMause-rOnHkqA9mC6yPBJc',
                'ProductiveLongRutabagaSMOrc-knInVjNGVlzyEoq9',
                'EndearingCrazyPepperoniEagleEye-DKddR1AmIcTylJAe',
                'ResoluteExpensiveStapleSpicyBoy-RlFRTJtGUihXjOcz',
                'YawningUgliestPresidentWow-B9ZLCeStVI5Tu1av',
                'AntsyGiantPenguinSquadGoals-CGs2SpKa1c2UwBKw',
                'ImpartialCrackyWebBloodTrail-LUS5LRt_S_4mepIr',
                'ConcernedTangibleOryxVoteYea-5rwu7O2ZhLr6di4C',
                'OddBlindingPuffinAliens-oQ97t1DQIK7DtnfX',
                'SmilingDistinctCakeDansGame-tVWqFK82lJeSerbO',
                'SpineyBillowingSushiNotATK-YbddYZZ2mrv-vAgf',
                'ManlyPrettyElephantDuDudu--Su7d54XIENigrcI',
            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 9',
            'slug' => 'episode-9',
            'youtube_url' => 'https://www.youtube.com/watch?v=vVHZEiCK8bE',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-03-13 16:00:00',
            'clips' => [
                'VibrantRudePuddingJonCarnage-c2kMcKVrHFdl0o5e',
                'VastPopularCarrotPMSTwin-k0GXchXFvUJKrJmz',
                'UglyModernEchidnaPogChamp-pDtrv9uu2h56s434',
                'TenaciousSmilingRamenOSkomodo-65Kt8EOcYJ3-FPyn',
                'TameColorfulJuiceAsianGlow-aLMZw1XrTdfsDi9V',
                'SuperYawningKuduYouDontSay-uyj5Qgi4I2L9DUBw',
                'SpoopyRoundPuffinFloof-9fTGuyzrB7gnsn9e',
                'SpicyLightBarracudaTheThing-4c1PmbE8QiYXtNJV',
                'SpeedyOnerousKleeBrokeBack-sG69TVYhIm5XwgN4',
                'SparklyDullMooseDancingBaby-W4i9MB5tDfA3SiyH',
                'SmoothJollyReindeerKeyboardCat-U7Shiztk9A9KInGX',
                'SingleColorfulSageWoofer-cfuIJ102ziUciuwZ',
                'SeductiveExcitedHawkLitFam-JSc7Cg2sIk9dtVMd',
                'RudeSingleWaffleBatChest-hctsrlpGVHI3PyNv',
                'RamshackleFreezingSushiCurseLit-Xhg7lNymu054NjiL',
                'PiliablePreciousFriesPartyTime-bQkEKR70YfWJfooR',
                'PeacefulClearLlamaPhilosoraptor-geadrpLzdbxFgOCa',
                'NeighborlyIntelligentEmuMingLee-VYK8H7C5U3q0lubH',
                'NeighborlyFamousYamFutureMan-YSGIEdNlpJeRF-dX',
                'MotionlessFrailEggKAPOW-_TLZbAsYIplU7ve2',
                'ManlyRelatedReubenTF2John-VWKnWb7AI2r7S8dU',
                'LachrymoseLightDiamondPlanking-IOz7U2ySvMW4c3ue',
                'LachrymoseFilthyPonySaltBae-A4WwhGJc89g3UAA-',
                'JollyGrotesqueQueleaTF2John-69Um7lJgMiEbqxGC',
                'IntelligentColdTildeVoHiYo-4BSv_xg__-nwCQAU',
                'HumbleCleanClintTBCheesePull-pPKJ_VQZTaQdsdRK',
                'HelpfulRelentlessZucchiniKippa-MwvXP_wm5UoFda7n',
                'FrailInnocentEyeballHumbleLife-qAXpnQimMA7Fg6Mq',
                'EnchantingSpookyClipzDatBoi-P7uJGWG1ru3G8pYx',
                'EmpathicGracefulCatKappaPride-V4aKWkpqSa3Z_6uP',
                'ElatedCuriousPepperoniFloof-emscHxhWG5Pav1gB',
                'DeadTenuousGoldfishTwitchRaid-Cr3db4HJTJuJgfJR',
                'ClearColdbloodedTitanAllenHuhu-hFsCpHHge6toGX3B',
                'ArborealViscousLatteTakeNRG-FC_GUGNM2IjEeOTJ',
                'AmusedAliveRamenTBCheesePull-YbpQkgs36gSvnIfQ',
                'AlertAltruisticEmuCharlietheUnicorn-51hJmLU-x5667OYQ',
                'AffluentSilkyLegDancingBanana-Z-Qyqzuk3mnkY7pf',
                'AbstemiousTenaciousDeerVoHiYo-FxvyzD0HVvNTKKT9',
            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 10',
            'slug' => 'episode-10',
            'youtube_url' => 'https://www.youtube.com/watch?v=SZJ_PRrw_io',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-03-20 16:00:00',
            'clips' => [
                'ResourcefulBoldTriangleFrankerZ-SvcOh35BcQ7Czhcl',
                'SteamyDullFennelTwitchRPG-8qAGdPhrudR-MxVT',
                'PlausibleFriendlyKangarooDancingBaby-GdyF8CHeEsxo_ysJ',
                'FrailTriumphantKiwiAMPEnergy-DozZNeUDyA6TKAVB',
                'RoundSplendidPterodactylArgieB8-19KvNUTqtSWOSdNn',
                'DarlingTentativeButterflyChefFrank-e0pvDCb45SrQVkcr',
                'PiercingTemperedLousePartyTime-sq_E2ABah-TTF8h_',
                'BeautifulLittleIcecreamSpicyBoy-EL4svSuyJ8imJPzg',
                'ExcitedGenerousRabbitPJSalt-mriAHrYRCJX7JYZ0',
                'ArtsyApatheticGoldfishPunchTrees-lyfC66CC3qbfqprM',
                'TawdryGlutenFreeSandwichAMPTropPunch-ajfXxeXgy_tn2sOD',
                'SmoothZealousBubbleteaFunRun-xFnkHEkMVBWy17NH',
                'CleanGleamingPonyAsianGlow-MSE0OIRo2riRXBUN',
                'MoldyCleverOctopusPanicVis-POKv0owfNwQk3r5R',
                'TransparentVibrantLarkOneHand-FXSF0Mdhj31FT63O',
                'ArborealSingleTrayVoteYea-3TelxU7aZo-WsKhZ',
                'CharmingFineZebraWutFace-owiIdQnnlUwtWJhI',
                'BlatantAnimatedSpindlePMSTwin-tLTrbaoTAsmiKy-q',
                'SucculentOutstandingCiderFUNgineer-yu-9XfOAJou16ZOc',
                'CleverCourteousLobsterLitFam-pVNMjaELqh0aWfAe',
                'FragileColdCrowGingerPower-xSZ12TTp30OswROp',
                'LuckyZanyDurianGOWSkull-p8pkHcNi-oTz-GaV',
                'FrigidCoweringJackalKreygasm-zT3CJLJhryg6OyIX',
                'BoredGoldenBaconTBCheesePull-ONvoHnjxoDNSOkBy',
                'ElegantSolidMallardTebowing-gcc7CWR6PXoMKXDC',
                'GiantSpineyCarrotDerp-xly9TsBJfPjWlOmE',
                'WonderfulFastTruffleBleedPurple-m8vL3A3NAGeoGei_',
                'CrowdedObeseCurlewRitzMitz-refDpDPdnGSFlGLa',
                'ImpossibleEnthusiasticAnacondaBibleThump-KB994jhp5cxwLvzE',
                'ElatedArtisticLyrebirdResidentSleeper-TuB-IMEavoxR7Fvw',
                'TangibleAmazingPotSquadGoals-vlEZC98AjZK1VqYH',
            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 11',
            'slug' => 'episode-11',
            'youtube_url' => 'https://www.youtube.com/watch?v=sX6A3FMLLeI',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-03-27 16:00:00',
            'clips' => [
                'MistyKitschyPartridgeYouWHY-anZflhPnVlaixb8N',
                'FilthyShinyCheese4Head-GUdl5IZiNNpZKlKF',
                'ShyRefinedReindeerSaltBae-bAAWKglbOJMuZA1K',
                'ThoughtfulRealOrcaMau5-LA6xWm5BESIu_VAV',
                'PhilanthropicTubularBibimbapPermaSmug-YHtXt80eXhTBn75x',
                'SmallClearPoultrySaltBae-3sdd8MDMP5UssNVG',
                'RacyLivelyVelociraptorSoonerLater-2ZznhHLpwQcoqXUE',
                'SpicyAmericanPepperoniYee-ZVocNMu5QVb_vQHs',
                'CovertSaltyTigerYee-UcOWZ1Oy7G7htwbz',
                'DarlingRoundWrenThisIsSparta-gjC0Rt7_Bxxhw8z6',
                'RelentlessFastFalconWoofer-HaX2UC1kFNJLGQQu',
                'CrowdedTrappedGooseBrainSlug-WFyYIHJseeZsZZ4q',
                'AggressiveBigWormKappaWealth--Pia0DoX6NuKVAev',
                'AltruisticEasyStingrayAliens-CSii__De3BRfX8H9',
                'OutstandingKnottyPorcupineSpicyBoy-ScNq8xOGEyjPqQia',
                'ArtisticTrappedDeerCurseLit-Ys9MsgR00ng8WXvi',
                'TalentedRichStorkTooSpicy-cymfMZOJuDmn3srK',
                'UglyResourcefulWaterNerfBlueBlaster-JEOZC9svHFjLl5nP',
                'WanderingCaringPepperoniPMSTwin-gbUglGcugF9AR3K8',
                'VibrantLivelyThymeJKanStyle-jpjKbY0ktjPLaQan',
                'AwkwardEasyTireDancingBaby-AZDSYSv6Mpk5URbz',
                'SpicyTriumphantDragonflyKevinTurtle-oiDaLBP2TtaAZFh3',
                'ObeseWrongFungusPeteZaroll-Xk3f0qOwXSfvfMFm',
                'StylishGiantMagpieGrammarKing-hLkoOpx2N3k1PrQg',
                'RoundSneakyPoultryBlargNaut-ob2PP0BZTjI2jmdl',
                'AdorableEntertainingEyeballNerfBlueBlaster-aiEvEp7yMZ2D3ymh',
                'MildAmorphousCodWow-Up7ycxTCpMwaucPL',
                'DelightfulSingleDragonfruitTwitchRPG-ThKhBHKlhfg_pyir',
                'SmellyCleanReindeerPanicBasket-x2l3wyk91-BDh1dl',
                'ManlyAnnoyingOpossumPupper-iqhiOpHpZbT1tm0l',
                'ObservantAgreeableBasenjiJonCarnage-y69OwUFBe26vqIYW',
                'DullBrightChowderHoneyBadger-613ziPcQYmyo_34Q',
                'JazzyRacyKumquatHotPokket-tJRq_rW0SH9pLWCY',
                'FastFrailRaccoonOhMyDog-olhCoUZckS91R6yc',
                'AdorableExpensiveDootKappaClaus-Tf0TawyCJEjkb-KB',
                'SincereMiniatureWatercressNononoCat-eYAZvE-Yt1EBJILk',
                'CoweringPlayfulKaleTBCheesePull-MasknB9DVmhQ04e8',
                'ToughBoringChimpanzeeKevinTurtle-RWaDsOP_I5eS7uM5',
                'BlushingScrumptiousWormLitty-Fx3l2GrN9Ekd3jvJ',
                'SquareBlightedPartridgePanicBasket-pFSv6nAVwfyfW0Mr',
                'BlatantEncouragingCurlewOSkomodo-PzF9XT7wwGDgkwcX',
                'ProductiveCrowdedLeopardM4xHeh-lddJY9UPqdEwuUYl',
                'StrangeHandsomeTrayHumbleLife-gzvGcR7oCChUgbP2',
            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 12',
            'slug' => 'episode-12',
            'youtube_url' => 'https://www.youtube.com/watch?v=eEmtkdHbqoI',
            'status' => CompilationStatus::Published,
            'created_at' => '2026-04-06 16:00:00',
            'clips' => [
                'CharmingLivelyArugulaItsBoshyTime-5scM02cVVc2PfQdA',
                'ExquisiteMotionlessDonkeyShadyLulu-_jGLka8eaKW6brMb',
                'GloriousCharmingGarlicCeilingCat-HTWdjOFYAWBPnTEL',
                'CrowdedHeartlessGrassHassanChop-GA2A_hykNybC6FwN',
                'HumbleGiftedDaikonDBstyle-49P3VvEFW0Y7b54i',
                'TrustworthyRudeTrayTBTacoLeft-rvUpFsciFAFUddaY',
                'DiligentRelievedHedgehogPicoMause-8vYWuabPBGX-W5Js',
                'CarelessKnottyTriangleFailFish-OvYXBGZw3T2ntD_1',
                'EndearingDirtySlothCurseLit-ROTiDEpIgUZhFKQc',
                'DeterminedPeacefulCookiePRChase-ORs5yu3S1QymYyUK',
                'RockyRacyDunlinPJSalt-R_OfrZPDKOpruZxN',
                'LittleTolerantReindeerKAPOW-fCMI5jT0lFSzrsL1',
                'BitterAlertGoatKappaClaus-Ijl-kmTL-oO1Gm4u',
                'HonorableHandsomeSeahorseMVGame-_2AHspx_4nOOWI55',
                'TenuousWildPorcupineTheRinger-6W8HXo8aAtSKXn6N',
                'RichSlipperyHamRedCoat-B7ADxf-nKaVIDW71',
                'MildEmpathicEggKappaWealth-x_j41s-c4vSIWYpx',
                'HorribleGrotesquePlumageDatSheffy-VWc466lISL1Lxuow',
                'WrongOilyPassionfruitCorgiDerp-3HyqLV-mmPmAzrh9',
                'HandsomeLittleBasenjiTBCheesePull-18roTmdyG4ptEa2x',
                'FantasticThankfulWatermelonGrammarKing-0yY7Nshj_uoE7xom',
                'NurturingIronicDumplingsAllenHuhu-FH0RKCXKs6iVeDy4',
                'TacitFantasticBadgerAMPEnergy-YfGXMw0HYGVCNNTV',
                'SlipperyNiceDaikonFloof-E2LR2FU_nwTkiCcc',
                'BlatantCleverLemurKappaRoss-YjqBo02ib6rIUgFj',
                'FlirtyAmusedAxeSmoocherZ-tg3tW1wxOXARCw44',
                'QuaintYawningDragonfruitCoolCat-CXWOEhqwTFW5kHDb',
                'PeacefulDoubtfulHyenaRitzMitz-o-YUo93-0gvsbLkW',
                'CleanBluePelicanBibleThump-fDg39asZY0lyhzFv',
                'IncredulousDeterminedCroquetteOhMyDog-LU_wQ_GIBn3EAsP-',
                'CarelessTenderSwordCoolStoryBro-3Ohklzx_6IK_XxYg',
                'ShortNeighborlyCobraSpicyBoy-GjJy22pqUox_op3C',
                'CooperativeAntediluvianLardDatBoi-i-czJmJPKSmUw4OF',
                'RenownedGiftedYogurtDuDudu-q8vw2NZaJzOq803S',

            ],
        ],
        [
            'user_id' => 0,
            'title' => 'Episode 13',
            'slug' => 'episode-13',
            'youtube_url' => '',
            'status' => CompilationStatus::Scheduled,
            'created_at' => '2026-04-10 16:00:00',
            'clips' => [
                'EnergeticTangibleMoonTheRinger-eCI91imaNBVXs-oX',
                'ObservantTrappedWasabiSoBayed-2eKof02ChTME3rdW',
                'BovineNurturingOctopusDatBoi-GyANGKJ3IKdYaajo',
                'DifficultGenerousFrogCorgiDerp-jmVMUec2KhDI9PHf',
                'LittleBlushingSardineTinyFace-ZI1sntTrUo0L7Rqy',
                'ExcitedLuckyCobblerRaccAttack-g9dn_VSKOK0NPecu',
                'SucculentHumbleLlamaDoritosChip-x-ID60Am3GcCUNX2',
                'AdorableObedientSkirretGivePLZ-l3Dr60Ml-mLjaSrm',
                'WrongSteamyOpossumCharlieBitMe--QsRx7vdMlciqbcc',
                'SmoothApatheticPizzaCmonBruh-DDNRLHqb7pL7TNp6',
                'FineGleamingDolphinTTours-zNnquC36elypfkUj',
                'ProductiveSecretiveChowderPanicBasket-YF_kOxYJC_gHoO70',
                'AmericanBrightMetalOpieOP-zd_kWqP1RoMfl5C9',
                'DeadThankfulKuduDeIlluminati-DdDMFclx-kDU4gna',
                'HeartlessApatheticConsoleNotATK-jrcvtXxVbLu8z4LE',
                'SincereInexpensiveChamoisBrainSlug-NbmwdYuc105d_rc-',
                'EntertainingSwissWitchOptimizePrime-EsddhzgbwHqYZgUF',
                'FlaccidIcyKumquatSwiftRage-SHJd9DiYaYNcL8rM',
                'WimpyBenevolentBearVoHiYo-DbZshTGk022O9SVE',
                'AcceptableMoldyFloofFeelsBadMan-Z7X1lHSzPawhpGDh',
                'MoralInquisitiveAnteaterGivePLZ-J2rTg6GBuCpWuSLe',
                'ResolutePeppyWrenchFUNgineer-I4gqdVbWp39MpkgY',
                'GoodCooperativeTortoiseFailFish-VdLnPcq0LiiVcAFL',
                'HardElatedTrufflePermaSmug-8qUX3jR7gmZTAxLa',
                'TangentialLivelyCheeseBloodTrail-4TKYiHPeQZOR-lAB',
                'WealthyPlainYogurtBrainSlug-f9I0qCl-aDgu-BVg',
                'ConsiderateFunAubergineTheThing-auGK5mzIijmwkWIB',
                'VibrantOddMomJebaited-KkkH2V9kEJql4xlY',
                'LazyShakingAyeayeDoritosChip-E-JCYbBtR4Kozy4G',
                'HelpfulFurtiveWoodcockDansGame-6blyqdG3yphMWGRV',
                'DrabOptimisticWheelYouWHY-sn1loGm1LiDft8jo',
                'CrispyHonorableAlfalfaOpieOP-Sy7qRsLl78i8cDre',
                'FrailPiercingCobblerAllenHuhu-F_XxAQpR9-luYtZR',
                'KitschyCautiousMonitorBuddhaBar-q7YaFWB8kyElG2ts',
                'TenuousSpoopyMuleBudStar-EVZvQEFiVnlwCbuM',
            ],
        ],
    ];

    /**
     * Run the database seeds.
     */
    public function run(ImportClipAction $importClipAction, TwitchService $twitchService): void
    {
        if (Compilation::count() > 0 || app()->environment('testing')) {
            return;
        }

        $systemUser = User::find(0);
        $allClips = collect(self::Clips);

        foreach (self::Episodes as $episode) {
            $allClips = $allClips->merge($episode['clips']);
        }

        $allClips = $allClips->values()->unique();
        $twitchClips = collect();
        $missingClips = collect();

        Log::notice("Importing {$allClips->count()} Clips...");
        $appTwitch = $twitchService->asApp();

        $allClips->chunk(100)->each(function ($chunk, $index) use ($appTwitch, &$twitchClips, &$missingClips): void {
            $requestedIds = $chunk->values()->toArray();
            $params = ['id' => $requestedIds];

            try {
                $clips = $appTwitch->getClips($params);

                $fetchedClips = collect($clips);

                $missingCount = count($requestedIds) - $fetchedClips->count();
                if ($missingCount > 0) {
                    $foundIds = $fetchedClips->pluck('id')->toArray();
                    $missingIds = array_diff($requestedIds, $foundIds);
                    $missingClips = $missingClips->merge($missingIds)->values()->unique();

                    Log::warning("Chunk {$index}: Requested ".count($requestedIds).' clips, but Twitch only returned '.$fetchedClips->count().'. Missing: '.implode(', ', $missingIds));
                } else {
                    Log::info("Chunk {$index}: Successfully fetched all ".count($requestedIds).' clips.');
                }

                $twitchClips = $twitchClips->merge($fetchedClips)->values();
            } catch (Exception $e) {
                Log::error('Twitch API Error: '.$e->getMessage());

                return;
            }

            sleep(1);
        });

        $twitchClips->each(function (ClipDto $clip) use ($systemUser, $importClipAction): void {
            $importClipAction->execute($clip, $systemUser);
        });

        Log::notice("{$twitchClips->count()} Clips have been imported.");

        foreach (self::Episodes as $episodeData) {
            /** @var Compilation $compilation */
            $compilation = Compilation::create([
                'user_id' => 0,
                'title' => $episodeData['title'],
                'slug' => $episodeData['slug'],
                'status' => $episodeData['status'],
                'type' => CompilationType::LongVideo,
                'youtube_url' => $episodeData['youtube_url'],
                'created_at' => $episodeData['created_at'] ?? now(),
                'updated_at' => now(),
            ]);

            $clips = Clip::query()
                ->withoutGlobalScope(ClipPermissionScope::class)
                ->whereIn('twitch_id', $episodeData['clips'])
                ->pluck('id')
                ->map(fn (int $id): array => [
                    'clip_id' => $id,
                    'added_by' => 0,
                    'claim_status' => CompilationClipClaimStatus::Completed,
                ]);

            $compilation->clips()->sync($clips);

            $clips->each(function (array $clip): void {
                DB::table('clips')->where('id', $clip['clip_id'])->update(['status' => ClipStatus::Approved]);
            });

            $compilation->comments()->create([
                'body' => "Compilation with {$clips->count()} clips has been imported.",
                'author_id' => $systemUser->getKey(),
                'author_type' => $systemUser->getMorphClass(),
            ]);
        }

        // Force-run the import Job because we are lazy
        ImportCategoryJob::dispatchSync([]);
    }
}
