name: Pull Request Validation

on:
  pull_request:
    types: [ opened, synchronize, reopened, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.filter.outputs.src }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: filter
        with:
          filters: |
            src:
              - '**/*.php'
              - '**/*.json'
              - 'composer.lock'
              - 'resources/**'
              - '*.xml'
              - '*.neon'
              - '*.ts'
              - '*.js'
              - '.env.ci'
              - '.npmrc'
  tests:
    needs: changes
    if: needs.changes.outputs.src == 'true' && (github.event.pull_request.draft == false || github.event_name == 'workflow_dispatch')
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      DB_CONNECTION: pgsql
      DB_DATABASE: laravel
      DB_USERNAME: postgres
      DB_PASSWORD: password
      BROADCAST_DRIVER: log
      CACHE_DRIVER: redis
      QUEUE_CONNECTION: redis
      SESSION_DRIVER: redis

    services:
      postgres:
        image: postgres:18-alpine
        env:
          POSTGRES_DB: laravel
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432/tcp
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:alpine
        ports:
          - 6379/tcp
        options: --health-cmd="redis-cli ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # v2.37.2
        with:
          php-version: '8.5'
          extensions: mbstring, dom, fileinfo, pdo_pgsql, redis
          coverage: none

      - name: Install PHP Dependencies
        uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version: '24'
          cache: 'npm'

      - name: Build Frontend Assets
        run: |
          npm ci
          npm run build

      - name: Prepare the application
        run: |
          cp .env.ci .env
          php artisan key:generate
          chmod -R +x vendor/bin

      - name: Clear Config
        run: php artisan config:clear

      - name: Dump Autoloader
        run: composer dump-autoload --optimize

      - name: Run Migration
        run: php artisan migrate:fresh --seed -v
        env:
          DB_PORT: ${{ job.services.postgres.ports['5432'] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}

      - name: Run PHP Unit Tests
        run: composer test
        env:
          DB_PORT: ${{ job.services.postgres.ports['5432'] }}
          REDIS_PORT: ${{ job.services.redis.ports['6379'] }}
